### ISSUE TITLE
搜索页面，搜索框中默认的“输入关键词”提示语是框的值，能否改成placeholder，这样不用每次手动删除。

### ISSUE THREAD

**Issue by robustmaster** [imjeff/wordpress-writing#1]
搜索页面，搜索框中默认的“输入关键词”提示语是框的值，能否改成placeholder，这样不用每次手动删除。

**Comment by imjeff** [comment]
> 搜索页面，搜索框中默认的“输入关键词”提示语是框的值，能否改成placeholder，这样不用每次手动删除。

已增加独立的搜索模板。
